export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

//LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
//ROOM
export const GET_ROOM_LIST = "GET_ROOM_LIST";

//STATE ROOM
export const GET_ROOM_STATE_LIST = "GET_ROOM_STATE_LIST";

//TYPE ROOM
export const GET_TYPE_ROOM = "GET_TYPE_ROOM";

//TYPE CUSTOMER
export const GET_TYPE_CUSTOMER = "GET_TYPE_CUSTOMER";

//REPORT
export const GET_REPORT = "GET_REPORT";

//INVOICE
export const GET_INVOICE_LIST = "GET_INVOICE_LIST";

//INVOICE LOCAL
export const GET_INVOICE_LOCAL = "GET_INVOICE_LOCAL";
export const ADD_ROOM_INVOICE_LOCAL = "ADD_ROOM_INVOICE_LOCAL";
export const REMOVE_ROOM_INVOICE_LOCAL = "REMOVE_ROOM_INVOICE_LOCAL";

//RENT VOUCHER
export const GET_RENT_VOUCHER_LIST = "GET_RENT_VOUCHER_LIST";

//RENT VOUCHER LIST LOCAL
export const GET_CLIENT_RENT_VOUCHER_LIST = "GET_CLIENT_RENT_VOUCHER_LIST";
export const REMOVE_CLIENT_RENT_VOUCER = "REMOVE_CLIENT_RENT_VOUCER";

//SURCHARGE
export const GET_SURCHARGE_LIST = "GET_SURCHARGE_LIST";

//CHECK OUT TIME
export const CHECK_IN_TIME = 13;
export const CHECK_OUT_TIME = 11;


