//ROOM
export const FETCH_LIST_ROOM_SAGA = "FECTH_LIST_ROOM_SAGA";
export const ADD_NEW_ROOM_SAGA = "ADD_NEW_ROOM_SAGA";

//TYPE ROOM
export const FECTH_LIST_TYPE_ROOM_SAGA = "FECTH_LIST_TYPE_ROOM";

//TYPE CUSTOMER
export const FETCH_LIST_TYPE_CUSTOMER = "FETCH_LIST_TYPE_CUSTOMER";