//ROOM
export const FETCH_LIST_ROOM_SAGA = "FECTH_LIST_ROOM_SAGA";
export const ADD_NEW_ROOM_SAGA = "ADD_NEW_ROOM_SAGA";
export const EDIT_ROOM_SAGA = "EDIT_ROOM_SAGA";
export const DELETE_ROOM_SAGA = "DELETE_ROOM_SAGA";

//STATE ROOM
export const FETCH_LIST_STATE_ROOM_SAGA = "FETCH_LIST_STATE_ROOM";

//TYPE ROOM
export const FECTH_LIST_TYPE_ROOM_SAGA = "FECTH_LIST_TYPE_ROOM";
export const ADD_TYPE_ROOM_SAGA = "ADD_TYPE_ROOM_SAGA";
export const EDIT_TYPE_ROOM_SAGA = "EDIT_TYPE_ROOM_SAGA";
export const DELETE_TYPE_ROOM_SAGA = "DELETE_TYPE_ROOM_SAGA";

//TYPE CUSTOMER
export const FETCH_LIST_TYPE_CUSTOMER_SAGA = "FETCH_LIST_TYPE_CUSTOMER_SAGA";
export const POST_TYPE_CUSTOMER_SAGA = "POST_TYPE_CUSTOMER_SAGA";