export const gridSpacing = 3;
export const drawerWidth = 260;
export const appDrawerWidth = 320;

//LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//USER
export const GET_USER = "GET_USER"
export const GET_USER_LIST = "GET_USER_LIST"
export const GET_USER_GROUP_LIST = "GET_USER_GROUP_LIST"
export const SET_RESET_STATE_1 = "SET_RESET_STATE_1"
export const SET_RESET_STATE_2 = "SET_RESET_STATE_2"

//ROOM
export const GET_ROOM_LIST = "GET_ROOM_LIST";

//STATE ROOM
export const GET_ROOM_STATE_LIST = "GET_ROOM_STATE_LIST";

//TYPE ROOM
export const GET_TYPE_ROOM = "GET_TYPE_ROOM";

//TYPE CUSTOMER
export const GET_TYPE_CUSTOMER = "GET_TYPE_CUSTOMER";

//REPORT
export const GET_REPORT = "GET_REPORT";
export const GET_REPORT_IN_YEAR = "GET_REPORT_IN_YEAR";

//INVOICE
export const GET_INVOICE_LIST = "GET_INVOICE_LIST";

//INVOICE LOCAL
export const GET_INVOICE_LOCAL = "GET_INVOICE_LOCAL";
export const ADD_ROOM_INVOICE_LOCAL = "ADD_ROOM_INVOICE_LOCAL";
export const REMOVE_ROOM_INVOICE_LOCAL = "REMOVE_ROOM_INVOICE_LOCAL";

//RENT VOUCHER
export const GET_RENT_VOUCHER_LIST = "GET_RENT_VOUCHER_LIST";
export const GET_RENT_VOUCHER_DETAIL = "GET_RENT_VOUCHER_DETAIL"

//RENT VOUCHER LIST LOCAL
export const GET_CLIENT_RENT_VOUCHER_LIST = "GET_CLIENT_RENT_VOUCHER_LIST";
export const REMOVE_CLIENT_RENT_VOUCER = "REMOVE_CLIENT_RENT_VOUCHER";
export const UPDATE_CLIENT_RENT_VOUCHER = "UPDATE_CLIENT_RENT_VOUCHER";

//SURCHARGE
export const GET_SURCHARGE_LIST = "GET_SURCHARGE_LIST";

//CONFIG
export const GET_CONFIG = "GET_CONFIG";

//CHECK OUT TIME
export const CHECK_IN_TIME = 13;
export const CHECK_OUT_TIME = 11;


