//USER
export const POST_USER_LOGIN_SAGA = "POST_USER_LOGIN_SAGA";
export const FETCH_LIST_USER_SAGA = "FETCH_LIST_USER_SAGA";
export const FETCH_LIST_USER_GROUP_SAGA = "FETCH_LIST_USER_GROUP_SAGA";
export const ADD_NEW_USER_SAGA = "ADD_NEW_USER_SAGA";
export const EDIT_USER_SAGA = "EDIT_USER_SAGA";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
export const FORGOT_PASSWORD_SAGA = "FORGOT_PASSWORD_SAGA";
export const RESET_PASSWORD_SAGA = "RESET_PASSWORD_SAGA";

//ROOM
export const FETCH_LIST_ROOM_SAGA = "FECTH_LIST_ROOM_SAGA";
export const ADD_NEW_ROOM_SAGA = "ADD_NEW_ROOM_SAGA";
export const EDIT_ROOM_SAGA = "EDIT_ROOM_SAGA";
export const DELETE_ROOM_SAGA = "DELETE_ROOM_SAGA";
export const FECTH_ALL_INFOR_FOR_ROOM = "FECTH_ALL_INFOR_FOR_ROOM";

//STATE ROOM
export const FETCH_LIST_STATE_ROOM_SAGA = "FETCH_LIST_STATE_ROOM";

//TYPE ROOM
export const FECTH_LIST_TYPE_ROOM_SAGA = "FECTH_LIST_TYPE_ROOM";
export const ADD_TYPE_ROOM_SAGA = "ADD_TYPE_ROOM_SAGA";
export const EDIT_TYPE_ROOM_SAGA = "EDIT_TYPE_ROOM_SAGA";
export const DELETE_TYPE_ROOM_SAGA = "DELETE_TYPE_ROOM_SAGA";

//TYPE CUSTOMER
export const FETCH_LIST_TYPE_CUSTOMER_SAGA = "FETCH_LIST_TYPE_CUSTOMER_SAGA";
export const ADD_TYPE_CUSTOMER_SAGA = "POST_TYPE_CUSTOMER_SAGA";
export const EDIT_TYPE_CUSTOMER_SAGA = "EDIT_TYPE_CUSTOMER_SAGA";
export const DELETE_TYPE_CUSTOMER_SAGA = "DELETE_TYPE_CUSTOMER_SAGA";

//REPORT
export const FETCH_REPORT_SAGA = "FETCH_REPORT_SAGA";
export const FETCH_REPORT_IN_YEAR_SAGA = "FETCH_REPORT_IN_YEAR_SAGA";
export const GET_REPORT_EXCEL = "GET_REPORT_EXCEL";

//INVOICE
export const FETCH_LIST_INVOICE_SAGA = "FETCH_LIST_INVOICE_SAGA";
export const ADD_NEW_INVOICE_SAGA = "ADD_NEW_INVOICE_SAGA";

//RENT VOUCHER
export const FETCH_LIST_RENT_VOUCHER_SAGA = "FETCH_LIST_RENT_VOUCHER_SAGA";
export const ADD_RENT_VOUCHER_SAGA = "ADD_RENT_VOUCHER_SAGA";
export const FETCH_RENT_VOUCHER_DETAIL_SAGA = "FETCH_RENT_VOUCHER_DETAIL_SAGA";

//CONFIG
export const GET_CONFIG_SAGA = "GET_CONFIG_SAGA";
export const UPDATE_CONFIG_SAGA = "UPDATE_CONFIG_SAGA";

//SURCHARGE
export const FETCH_LIST_SURCHARGE_SAGA = "FETCH_LIST_SURCHASE_SAGA";
export const ADD_NEW_SURCHARGE_SAGA = "ADD_NEW_SURCHARGE";
export const EDIT_SURCHARGE_SAGA = "EDIT_SURCHARGE_SAGA";
export const DELETE_SURCHARGE_SAGA = "DELETE_SURCHARGE_SAGA";